[2014-05-29 17:00:41.754907]
ERROR
	"[Failure instance: Traceback from remote host -- Traceback unavailable\nexceptions.AttributeError: 'NoneType' object has no attribute 'level'\n]"
[2014-05-29 17:00:47.726628]
ERROR
	"[Failure instance: Traceback from remote host -- Traceback unavailable\nexceptions.AttributeError: 'NoneType' object has no attribute 'level'\n]"
[2014-05-29 17:00:48.545769]
ERROR
	"[Failure instance: Traceback from remote host -- Traceback unavailable\nexceptions.AttributeError: 'NoneType' object has no attribute 'level'\n]"
[2014-05-29 17:00:48.955058]
ERROR
	"[Failure instance: Traceback from remote host -- Traceback unavailable\nexceptions.AttributeError: 'NoneType' object has no attribute 'level'\n]"
[2014-05-29 17:01:59.409191]
ERROR
	"[Failure instance: Traceback from remote host -- Traceback unavailable\nexceptions.AttributeError: 'NoneType' object has no attribute 'level'\n]"
