[2014-02-24 18:55:20.995288]
ERROR
	"[Failure instance: Traceback from remote host -- Traceback unavailable\nexceptions.NameError: global name 'ShopPackage' is not defined\n]"
